import type { User, Quest, PetStageConfig } from '@/lib/types'

export const petStageConfig: PetStageConfig[] = [
  { stage: 1, minPoints: 0,  maxPoints: 4,    label: '알 (Egg)',        emoji: '🥚' },
  { stage: 2, minPoints: 5,  maxPoints: 19,   label: '아기 트리니티',    emoji: '🐣' },
  { stage: 3, minPoints: 20, maxPoints: null, label: '메가 트리니티',    emoji: '✨' },
]

export const initialUser: User = {
  id: 'user-1',
  name: '김신입',
  type: '공채',
  points: 0,
  petStage: 1,
  title: '',
}

export const initialQuests: Quest[] = [
  // daily-monthly (available) — 5+2+2 = 9P
  {
    id: 'meeting-room-qr',
    category: 'daily-monthly',
    title: '회의실 QR 체크인',
    description: '회의실 QR 코드를 스캔하여 매너 사용을 확인하세요.',
    rewardPoints: 5,
    status: 'available',
  },
  {
    id: 'email-check',
    category: 'daily-monthly',
    title: '업무 메일 확인',
    description: '오늘의 업무 메일을 확인하고 회신이 필요한 메일에 답장하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'e-approval',
    category: 'daily-monthly',
    title: '전자결재 확인',
    description: '전자결재 시스템에서 대기 중인 결재 항목을 확인하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  // hr-beginner (available) — 3+3+2+2+3 = 13P (5개)
  {
    id: 'hr-policy',
    category: 'hr-beginner',
    title: '인사제도 확인',
    description: '사내 인사제도 및 복리후생 내용을 확인하세요.',
    rewardPoints: 3,
    status: 'available',
  },
  {
    id: 'office-tour',
    category: 'hr-beginner',
    title: '오피스 투어',
    description: '사무실 주요 시설(회의실, 휴게실, 편의시설)을 둘러보세요.',
    rewardPoints: 3,
    status: 'available',
  },
  {
    id: 'profile-setup',
    category: 'hr-beginner',
    title: '프로필 설정',
    description: '사내 시스템에 프로필 사진과 기본 정보를 등록하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'hr-beginner-business-card',
    category: 'hr-beginner',
    title: '명함 신청',
    description: '그룹웨어 "명함신청서" 양식에 영문명, 연락처, 명함신청사유를 작성해 기안하세요. 직급 기재가 필요한 경우 "명함신청서(외부용)"을 사용하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'hr-beginner-employee-card',
    category: 'hr-beginner',
    title: '인사카드 작성/제출',
    description: '인사팀이 메일로 안내한 구글 스프레드시트 인사카드 양식을 작성하고, 소속 리더와 인사팀에 편집자 권한으로 공유하세요.',
    rewardPoints: 3,
    status: 'available',
  },
  // role-specific (locked) — 5+5+3 = 13P
  {
    id: 'slack-jira',
    category: 'role-specific',
    title: '슬랙/지라 권한 신청',
    description: '업무에 필요한 슬랙 채널 접근 및 지라 프로젝트 권한을 신청하세요.',
    rewardPoints: 5,
    status: 'available',
  },
  {
    id: 'msp-training',
    category: 'role-specific',
    title: 'MSP 기초 교육',
    description: 'MSP(Managed Service Provider) 기초 교육 과정을 이수하세요.',
    rewardPoints: 5,
    status: 'available',
  },
  {
    id: 'ctu-intro',
    category: 'role-specific',
    title: 'CTU 소개',
    description: 'CTU(Cloud Technology Unit) 조직 소개 자료를 확인하세요.',
    rewardPoints: 3,
    status: 'available',
  },

  // ── Stage 1: Pre-boarding (available) ── 합계 11P ──────────────────────────
  {
    id: 'pre-boarding-docs',
    category: 'pre-boarding',
    title: '입사 서류 제출',
    description: '주민등록등본, 졸업증명서, 통장사본 등 필수 입사 서류를 HR 포탈에 제출하세요.',
    rewardPoints: 3,
    status: 'available',
  },
  {
    id: 'pre-boarding-security-agreement',
    category: 'pre-boarding',
    title: '보안 서약서 작성',
    description: '보안 서약서 및 개인정보 수집·이용 동의서를 작성하고 제출하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'pre-boarding-account-setup',
    category: 'pre-boarding',
    title: '사내 계정 생성',
    description: '업무용 이메일, 메신저, 사내 포탈 계정을 생성하고 초기 비밀번호를 변경하세요.',
    rewardPoints: 3,
    status: 'available',
  },
  {
    id: 'pre-boarding-profile-photo',
    category: 'pre-boarding',
    title: '프로필 사진 등록',
    description: '사내 시스템에 프로필 사진을 등록하세요.',
    rewardPoints: 1,
    status: 'available',
  },
  {
    id: 'pre-boarding-self-intro',
    category: 'pre-boarding',
    title: '자기소개서 작성',
    description: '사내 게시판에 게시될 자기소개를 작성하고 등록하세요.',
    rewardPoints: 2,
    status: 'available',
  },

  // ── Stage 2: Day 1 ── 합계 22P (11개) ─────────────────────────────────────
  {
    id: 'day-one-id-card',
    category: 'day-one',
    title: '사원증 수령',
    description: '총무팀에서 사원증 및 출입카드를 수령하고 등록하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'day-one-workstation',
    category: 'day-one',
    title: '장비 세팅',
    description: '메가존빌딩 B1 IT Helpdesk에서 노트북을 수령하고(부서 사전 신청 시 모니터 등 추가 장비 포함), 배정된 자리에서 초기 세팅을 완료하세요.',
    rewardPoints: 3,
    status: 'available',
  },
  {
    id: 'day-one-wifi-vpn',
    category: 'day-one',
    title: 'Wi-Fi / VPN 연결',
    description: '사내 Wi-Fi에 접속하고 VPN을 설치하여 정상 연결을 확인하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'day-one-team-intro',
    category: 'day-one',
    title: '팀원 인사',
    description: '소속 팀원 전원에게 인사하고 자기소개를 완료하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'day-one-office-tour',
    category: 'day-one',
    title: '사무실 투어',
    description: '회의실, 휴게실, 식당, 비상구 위치를 파악하고 투어를 완료하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'day-one-buddy',
    category: 'day-one',
    title: '버디(Buddy) 찾아가기',
    description: '입사 전 지정된 버디를 첫날 OJT 후 부서에서 확인하고, 온보딩 질문을 정리해 첫 버디 미팅을 진행하세요. (신규 입사자당 30만 원 버디 활동비 지원)',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'day-one-pops-login',
    category: 'day-one',
    title: '메가존 PoPs 로그인',
    description: '부여된 임직원 Google 계정으로 Megazone PoPs(start.megazone.com)에 로그인하여 메가존 얼라이언스 조직 접근을 확인하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'day-one-megaone-ask',
    category: 'day-one',
    title: '메가원 Ask 접속',
    description: '메가원 Ask에 접속해 문의/업무 신청 채널을 확인하세요. (승인이 필요한 전자결재는 그룹웨어에서 처리)',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'day-one-megaone-groupware',
    category: 'day-one',
    title: '메가원 그룹웨어 접속',
    description: '그룹웨어(gw.megaone.com)에 접속해 조직도, 게시판, 전자결재, 휴가·경비 신청 메뉴를 확인하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'day-one-email-signature',
    category: 'day-one',
    title: '이메일 서명 설정',
    description: 'mzcloud_signature HTML 파일을 크롬에서 다운로드한 후 전체 선택(Ctrl+A) → 복사(Ctrl+C) → Gmail 설정 > 기본 설정 > 서명란에 붙여넣기(Ctrl+V)하여 서명을 등록하세요.',
    rewardPoints: 2,
    status: 'available',
    helpUrl: 'https://help.megaone.com/hc/ko/articles/10838538984857-6-%EC%9D%B4%EB%A9%94%EC%9D%BC-%EC%84%9C%EB%AA%85-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0',
  },
  {
    id: 'day-one-printer-setup',
    category: 'day-one',
    title: '프린터/스캐너 설정',
    description: '그룹웨어 "총무업무 게시판"의 프린트 설치 가이드를 따라 사내 프린터/스캐너를 설정하세요.',
    rewardPoints: 1,
    status: 'available',
  },

  // ── Stage 3: Mandatory Training (locked) ── 합계 14P ───────────────────────
  {
    id: 'training-security',
    category: 'mandatory-training',
    title: '정보보안 교육',
    description: '정보보안 온라인 교육을 이수하고 수료증을 제출하세요.',
    rewardPoints: 3,
    status: 'available',
  },
  {
    id: 'training-sexual-harassment',
    category: 'mandatory-training',
    title: '성희롱 예방 교육',
    description: '성희롱 예방 교육을 이수하고 수료증을 제출하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'training-workplace-bullying',
    category: 'mandatory-training',
    title: '직장 내 괴롭힘 예방 교육',
    description: '직장 내 괴롭힘 예방 교육을 이수하고 수료증을 제출하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'training-safety-health',
    category: 'mandatory-training',
    title: '안전보건 교육',
    description: '산업안전보건 교육을 이수하고 수료증을 제출하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'training-privacy',
    category: 'mandatory-training',
    title: '개인정보 보호 교육',
    description: '개인정보 보호 온라인 교육을 이수하고 수료증을 제출하세요.',
    rewardPoints: 2,
    status: 'available',
  },
  {
    id: 'training-systems',
    category: 'mandatory-training',
    title: '사내 시스템 교육',
    description: '그룹웨어, 근태관리, 경비처리 시스템 사용법 교육을 이수하세요.',
    rewardPoints: 3,
    status: 'available',
  },

  // ── Stage 4: Know Your Company (locked) ── 합계 5P (추가 예정) ─────────────
  {
    id: 'culture-vision-quiz',
    category: 'company-culture',
    title: '회사 비전/미션 퀴즈',
    description: '회사 비전, 미션, 핵심 가치를 학습하고 퀴즈를 완료하세요.',
    rewardPoints: 3,
    status: 'available',
  },
  {
    id: 'culture-org-chart',
    category: 'company-culture',
    title: '조직도 파악',
    description: '사내 포탈에서 전체 조직도를 확인하고 주요 부서 역할을 파악하세요.',
    rewardPoints: 2,
    status: 'available',
  },
]
// 전체 합계: 87P (35개)
// pre-boarding: 11P (5개)
// day-one: 22P (11개) | mandatory-training: 14P (6개) | company-culture: 5P (2개)
// hr-beginner: 13P (5개) | role-specific: 13P (3개) | daily-monthly: 9P (3개)
