import type { ShopItem } from '@/lib/types'

export const shopItems: ShopItem[] = [
  {
    id: 'starbucks-americano',
    name: '아메리카노 T',
    brand: '스타벅스',
    description: '톨 사이즈 아메리카노',
    pointCost: 5,
    emoji: '☕',
    category: 'cafe',
  },
  {
    id: 'mega-coffee',
    name: '아메리카노 L',
    brand: '메가커피',
    description: '라지 사이즈 아메리카노',
    pointCost: 2,
    emoji: '🧋',
    category: 'cafe',
  },
  {
    id: 'baskin-robbins-single',
    name: '싱글 레귤러',
    brand: '배스킨라빈스',
    description: '싱글 레귤러 1스쿱',
    pointCost: 3,
    emoji: '🍦',
    category: 'food',
  },
  {
    id: 'burger-king-whopper',
    name: '와퍼 세트',
    brand: '버거킹',
    description: '와퍼 + 감자튀김 + 음료',
    pointCost: 8,
    emoji: '🍔',
    category: 'food',
  },
  {
    id: 'cu-3000',
    name: '편의점 3,000원권',
    brand: 'CU',
    description: 'CU 편의점 상품권',
    pointCost: 3,
    emoji: '🏪',
    category: 'convenience',
  },
  {
    id: 'cu-5000',
    name: '편의점 5,000원권',
    brand: 'CU',
    description: 'CU 편의점 상품권',
    pointCost: 5,
    emoji: '🏪',
    category: 'convenience',
  },
  {
    id: 'cgv-ticket',
    name: '영화 관람권',
    brand: 'CGV',
    description: '일반 2D 영화 1매',
    pointCost: 12,
    emoji: '🎬',
    category: 'culture',
  },
  {
    id: 'giftcard-10000',
    name: '문화상품권 1만원',
    brand: '문화상품권',
    description: '온·오프라인 공용 문화상품권',
    pointCost: 10,
    emoji: '🎁',
    category: 'etc',
  },
]
